### ISSUE TITLE
Uncaught TypeError: Cannot read property 'buffer' of undefined

### ISSUE THREAD

**Issue by jjlorenzo** [alexandruionascu/coconut#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [coconut](https://github.com/alexandruionascu/coconut) package, v0.11.0
### Stack Trace

Uncaught TypeError: Cannot read property 'buffer' of undefined

```
At /Users/jjlorenzo/.atom/packages/coconut/lib/coconut.coffee:153

TypeError: Cannot read property 'buffer' of undefined
    at Object.module.exports.Coconut.addStartSessionEvent (/Users/jjlorenzo/.atom/packages/coconut/lib/coconut.coffee:153:64)
    at Object.module.exports.Coconut.startSession (/Users/jjlorenzo/.atom/packages/coconut/lib/coconut.coffee:293:8)
    at atom-workspace.subscriptions.add.atom.commands.add.coconut:startSession (/Users/jjlorenzo/.atom/packages/coconut/lib/coconut.coffee:97:87)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -0:10.3.0 command-palette:toggle (atom-pane.pane.active)
     -0:09.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:09.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:03.5.0 coconut:startSession (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.0
atom-django, v0.3.0
autocomplete-sass, v0.1.0
coconut, v0.11.0
color-picker, v2.0.12
django-atom, v0.2.4
emmet-simplified, v2.5.0
swap-panes, v0.2.0
symbols-tree-view, v0.10.0

# Dev
No dev packages
```

**Comment by alexandruionascu** [comment]
Oh yes, I've almost forgot...You need an active window in order to start pairing. Probably you better start with a new untitled file, initial sync works decent but it is also a little buggy...Thank you very much for posting the problem :D

**Comment by ghost** [comment]
Can you send me some information about how to setup the server? I like the idea of having a secure collaborator, but I would rather use my server keys instead of yours.
