### ISSUE TITLE
Uncaught Error: Empty key given

### ISSUE THREAD

**Issue by ghost** [alexandruionascu/coconut#2]
[Enter steps to reproduce below:]
1. Started Atom
2. Click join session ( with files open ).

**Atom Version**: 1.7.4
**System**: linux 4.5.4-1-ARCH
**Thrown From**: [coconut](https://github.com/alexandruionascu/coconut) package, v0.11.0
### Stack Trace

Uncaught Error: Empty key given

```
At /home/larry/.atom/packages/coconut/node_modules/node-rsa/src/NodeRSA.js:172

Error: Empty key given
    at Error (native)
    at NodeRSA.module.exports.NodeRSA.importKey (/home/larry/.atom/packages/coconut/node_modules/node-rsa/src/NodeRSA.js:172:19)
    at /home/larry/.atom/packages/coconut/lib/coconut.coffee:194:11
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:692:27)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:877:16)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:831:14)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1274:26)
    at /usr/share/atom/resources/app.asar/src/text-editor.js:868:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:2170:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:2132:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/share/atom/resources/app.asar/src/text-editor.js:866:19)
    at TextEditor.module.exports.TextEditor.insertText (/usr/share/atom/resources/app.asar/src/text-editor.js:832:19)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/usr/share/atom/resources/app.asar/src/text-editor-component.js:474:35)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/src/text-editor-component.js:3:61)
```
### Commands

```
     -1:45.8.0 tabs:split-right (div.title)
     -0:48 coconut:joinSession (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-bash-builtins, v0.3.4
autocomplete-python, v1.7.3
clang-format, v1.25.0
coconut, v0.11.0
gpp-compiler, v2.3.1
java-class-complete, v0.0.6
language-actionscript, v0.2.0
language-actionscript3, v0.3.0
language-cpp14, v0.6.1
language-fish-shell, v1.0.4
language-pascal, v0.18.1
language-rpm-spec, v0.9.0
language-rspec, v0.5.0
linter, v1.11.4
php-integrator-annotations, v0.4.1
php-integrator-autocomplete-plus, v0.8.1
php-integrator-base, v0.9.3
php-integrator-call-tips, v0.2.4
php-integrator-linter, v0.3.0
php-integrator-navigation, v0.7.1
php-integrator-refactoring, v0.5.0
php-integrator-tooltips, v0.6.1

# Dev
No dev packages
```

**Comment by alexandruionascu** [comment]
I think I deleted the heroku app for the server, sorry, you can set up your own server or deploy another one to heroku or other provider, thanks
